services:
  - type: web
    name: maze-game
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: cd src && gunicorn maze_game.app:app
    envVars:
      - key: PYTHON_VERSION
        value: "3.13.4"
